### ISSUE TITLE
volumes needs to be recreated

### ISSUE THREAD

**Issue by hemertje** [timoknapp/rpi-nas#1]
Hi Timo,

with the stack below I get the error:

Volume "X" needs to be recreated - driver has changed.

=======================
- Removed Portainer as it is already running onder OMV
- Removed Plex as I don't use it
- Removed homeassistant as I don't use it

What needs to be added to get these following Apps running under the Portainer?

volumes:
  nextcloud_postgres: ?
  nextcloud: ?
  grafana-storage: ?
  influxdb-storage: ?

networks:
  influxdb: ?

=======================
version: "2"

services:
  heimdall: # Dashboard for all you Apps
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /dev-disk-by-label-data/AppData/heimdall:/config
    ports:
      - 8080:80
      - 443:443
    restart: unless-stopped

  portainer: # UI based management of Docker
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  cloudcmd: # UI based filemanager
    image: team0/rpi-cloudcmd # arm-based docker images for cloudcmd
    container_name: cloudcmd
    ports:
      - 8008:8000
    volumes:
      - ~:/root
      - /:/mnt/fs

  pyload: # pyload - download manager for your NAS
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /dev-disk-by-label-data/AppData/pyload:/config
      - /dev-disk-by-label-data/AppData/downloads:/downloads
    ports:
      - 8088:8000
      - 7227:7227 #optional
    restart: unless-stopped

  nextcloud_postgres: # DB for Nextcloud
    image: postgres
    container_name: nextcloud_postgres
    restart: always
    volumes:
      - nextcloud_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ABCDE12345
      - POSTGRES_DATABASE=nextcloud
      - POSTGRES_USER=nextcloud

  nextcloud: # Nextcloud
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8081:80
    links:
      - postgres
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped

  ## Monitoring Stack:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    command: --config-directory /etc/telegraf/telegraf.d
    depends_on:
      - influxdb
    networks:
      - influxdb
    volumes:
      - ./monitoring/telegraf:/etc/telegraf
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      influxdb:
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  nextcloud_postgres:
  nextcloud:
  grafana-storage:
  influxdb-storage:

networks:
  influxdb:

=======================

Thank you for you reply!

**Comment by hemertje** [comment]
have a look here:

https://github.com/portainer/portainer/issues/2289

https://github.com/docker/libcompose/issues/509

**Comment by hemertje** [comment]
some more :

https://github.com/portainer/portainer/issues/3750

**Comment by timoknapp** [comment]
> Hi Timo,
> 
> with the stack below I get the error:
> 
> Volume "X" needs to be recreated - driver has changed.
> 
> =======================
> 
>     * Removed Portainer as it is already running onder OMV
> 
>     * Removed Plex as I don't use it
> 
>     * Removed homeassistant as I don't use it
> 
> 
> What needs to be added to get these following Apps running under the Portainer?
> 
> volumes:
> nextcloud_postgres: ?
> nextcloud: ?
> grafana-storage: ?
> influxdb-storage: ?
> 
> networks:
> influxdb: ?
> 
> =======================
> version: "2"
> 
> services:
> heimdall: # Dashboard for all you Apps
> image: linuxserver/heimdall
> container_name: heimdall
> environment:
> - PUID=998
> - PGID=100
> - TZ=Europe/Amsterdam
> volumes:
> - /dev-disk-by-label-data/AppData/heimdall:/config
> ports:
> - 8080:80
> - 443:443
> restart: unless-stopped
> 
> portainer: # UI based management of Docker
> image: portainer/portainer
> container_name: portainer
> command: -H unix:///var/run/docker.sock
> restart: unless-stopped
> ports:
> - 9000:9000
> - 8000:8000
> volumes:
> - /var/run/docker.sock:/var/run/docker.sock
> - portainer_data:/data
> 
> cloudcmd: # UI based filemanager
> image: team0/rpi-cloudcmd # arm-based docker images for cloudcmd
> container_name: cloudcmd
> ports:
> - 8008:8000
> volumes:
> - ~:/root
> - /:/mnt/fs
> 
> pyload: # pyload - download manager for your NAS
> image: linuxserver/pyload
> container_name: pyload
> environment:
> - PUID=998
> - PGID=100
> - TZ=Europe/Amsterdam
> volumes:
> - /dev-disk-by-label-data/AppData/pyload:/config
> - /dev-disk-by-label-data/AppData/downloads:/downloads
> ports:
> - 8088:8000
> - 7227:7227 #optional
> restart: unless-stopped
> 
> nextcloud_postgres: # DB for Nextcloud
> image: postgres
> container_name: nextcloud_postgres
> restart: always
> volumes:
> - nextcloud_postgres:/var/lib/postgresql/data
> environment:
> - POSTGRES_PASSWORD=ABCDE12345
> - POSTGRES_DATABASE=nextcloud
> - POSTGRES_USER=nextcloud
> 
> nextcloud: # Nextcloud
> image: nextcloud
> container_name: nextcloud
> ports:
> - 8081:80
> links:
> - postgres
> volumes:
> - nextcloud:/var/www/html
> restart: unless-stopped
> ## Monitoring Stack:
> 
> telegraf:
> image: telegraf:latest
> container_name: telegraf
> command: --config-directory /etc/telegraf/telegraf.d
> depends_on:
> - influxdb
> networks:
> - influxdb
> volumes:
> - ./monitoring/telegraf:/etc/telegraf
> restart: always
> 
> influxdb:
> image: influxdb:latest
> container_name: influxdb
> networks:
> influxdb:
> volumes:
> - influxdb-storage:/var/lib/influxdb
> restart: unless-stopped
> 
> grafana:
> image: grafana/grafana:latest
> container_name: grafana
> depends_on:
> - influxdb
> ports:
> - 3000:3000
> networks:
> - influxdb
> environment:
> - GF_INSTALL_PLUGINS=grafana-piechart-panel
> volumes:
> - grafana-storage:/var/lib/grafana
> - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
> restart: unless-stopped
> 
> volumes:
> nextcloud_postgres:
> nextcloud:
> grafana-storage:
> influxdb-storage:
> 
> networks:
> influxdb:
> 
> =======================
> 
> Thank you for you reply!

Hi @hemertje ,

it seem that you have already some volumes running, which now blocks the recreation of new ones. Please review all mounted volumes and maybe remove them. In order to get the `docker-stack` running with your selected containers, you should start a `docker-compose.yml`with the following content. **IMPORTANT:** keep in mind to **update all relevant placeholders!** 

```
version: "2"

services:
  heimdall: # Dashboard for all you Apps
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Berlin
    volumes:
      - ${PATH_TO_DISK}/appdata/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  cloudcmd: # UI based filemanager
    image: team0/rpi-cloudcmd # arm-based docker images for cloudcmd
    container_name: cloudcmd
    ports:
      - 8008:8000
    volumes:
      - ~:/root
      - /:/mnt/fs

  pyload: # pyload - download manager for your NAS
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Berlin
    volumes:
      - ${PATH_TO_DISK}/appdata:/config
      - ${PATH_TO_DISK}/downloads:/downloads
    ports:
      - 8088:8000
      - 7227:7227 #optional
    restart: unless-stopped

  nextcloud_postgres: # DB for Nextcloud
    image: postgres
    container_name: nextcloud_postgres
    restart: always
    volumes:
      - nextcloud_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=nextcloud
      - POSTGRES_USER=nextcloud

  nextcloud: # Nextcloud
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8081:80
    links:
      - postgres
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped

  ## Monitoring Stack:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    command: --config-directory /etc/telegraf/telegraf.d
    depends_on:
      - influxdb
    networks:
      - influxdb
    volumes:
      - ./monitoring/telegraf:/etc/telegraf
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      influxdb:
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  nextcloud_postgres:
  nextcloud:
  grafana-storage:
  influxdb-storage:

networks:
  influxdb:
```

**Comment by hemertje** [comment]
All volumes removed:

<img width="1429" alt="Schermafbeelding 2020-04-30 om 14 18 45" src="https://user-images.githubusercontent.com/45018786/80710827-ac415100-8aef-11ea-84a1-800e6bd479bb.png">
<img width="1422" alt="Schermafbeelding 2020-04-30 om 14 18 57" src="https://user-images.githubusercontent.com/45018786/80710830-ad727e00-8aef-11ea-85d9-d4117ed3f620.png">
<img width="1424" alt="Schermafbeelding 2020-04-30 om 14 19 07" src="https://user-images.githubusercontent.com/45018786/80710832-ad727e00-8aef-11ea-9108-414900393aa6.png">
<img width="1424" alt="Schermafbeelding 2020-04-30 om 14 19 20" src="https://user-images.githubusercontent.com/45018786/80710836-ae0b1480-8aef-11ea-8256-803bfdab51c9.png">
<img width="1432" alt="Schermafbeelding 2020-04-30 om 14 19 42" src="https://user-images.githubusercontent.com/45018786/80710838-ae0b1480-8aef-11ea-903a-448a80e79102.png">

Question:
To start a `docker-compose.yml` I copy the `code`as a new stack en run "deploy the stack" right?
So to start a `docker-compose.yml` I create a new stack, name it "nas" and I copied under "stack" the following, one on one:


> version: "2"
> 
> services:
>   heimdall: # Dashboard for all you Apps
>     image: linuxserver/heimdall
>     container_name: heimdall
>     environment:
>       - PUID=998
>       - PGID=100
>       - TZ=Europe/Amsterdam
>     volumes:
>       - /dev-disk-by-label-data/AppData/Heimdall:/config
>     ports:
>       - 8080:80
>       - 443:443
>     restart: unless-stopped
> 
>   cloudcmd: # UI based filemanager
>     image: team0/rpi-cloudcmd # arm-based docker images for cloudcmd
>     container_name: cloudcmd
>     ports:
>       - 8008:8000
>     volumes:
>       - ~:/root
>       - /:/mnt/fs
> 
>   pyload: # pyload - download manager for your NAS
>     image: linuxserver/pyload
>     container_name: pyload
>     environment:
>       - PUID=998
>       - PGID=100
>       - TZ=Europe/Amsterdam
>     volumes:
>       - /dev-disk-by-label-data/AppData/pyload:/config
>       - /dev-disk-by-label-data/Downloads:/Downloads
>     ports:
>       - 8088:8000
>       - 7227:7227 #optional
>     restart: unless-stopped
> 
>   nextcloud_postgres: # DB for Nextcloud
>     image: postgres
>     container_name: nextcloud_postgres
>     restart: always
>     volumes:
>       - nextcloud_postgres:/var/lib/postgresql/data
>     environment:
>       - POSTGRES_PASSWORD=ABC123
>       - POSTGRES_DATABASE=nextcloud
>       - POSTGRES_USER=nextcloud
> 
>   nextcloud: # Nextcloud
>     image: nextcloud
>     container_name: nextcloud
>     ports:
>       - 8081:80
>     links:
>       - postgres
>     volumes:
>       - nextcloud:/var/www/html
>     restart: unless-stopped
> 
>   ## Monitoring Stack:
>   telegraf:
>     image: telegraf:latest
>     container_name: telegraf
>     command: --config-directory /etc/telegraf/telegraf.d
>     depends_on:
>       - influxdb
>     networks:
>       - influxdb
>     volumes:
>       - ./monitoring/telegraf:/etc/telegraf
>     restart: always
> 
>   influxdb:
>     image: influxdb:latest
>     container_name: influxdb
>     networks:
>       influxdb:
>     volumes:
>       - influxdb-storage:/var/lib/influxdb
>     restart: unless-stopped
> 
>   grafana:
>     image: grafana/grafana:latest
>     container_name: grafana
>     depends_on:
>       - influxdb
>     ports:
>       - 3000:3000
>     networks:
>       - influxdb
>     environment:
>       - GF_INSTALL_PLUGINS=grafana-piechart-panel
>     volumes:
>       - grafana-storage:/var/lib/grafana
>       - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
>     restart: unless-stopped
> 
> volumes:
>   nextcloud_postgres:
>   nextcloud:
>   grafana-storage:
>   influxdb-storage:
> 
> networks:
>   influxdb:


Now I am getting the error:

Service 'nextcloud' has a link to service 'postgres' which is undefined

<img width="1183" alt="Schermafbeelding 2020-04-30 om 14 48 57" src="https://user-images.githubusercontent.com/45018786/80712235-f62b3680-8af1-11ea-95bc-95974b1819d2.png">

**Comment by timoknapp** [comment]
Just noticed, that there is a typo in the `nextcloud` part. The reference under `links` must be `nextcloud_postgres` instead of `postgres`.

So again, here would be an appriate`compose` file for you:
```
version: "2"

services:
  heimdall: # Dashboard for all you Apps
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Berlin
    volumes:
      - ${PATH_TO_DISK}/appdata/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  cloudcmd: # UI based filemanager
    image: team0/rpi-cloudcmd # arm-based docker images for cloudcmd
    container_name: cloudcmd
    ports:
      - 8008:8000
    volumes:
      - ~:/root
      - /:/mnt/fs

  pyload: # pyload - download manager for your NAS
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Berlin
    volumes:
      - ${PATH_TO_DISK}/appdata:/config
      - ${PATH_TO_DISK}/downloads:/downloads
    ports:
      - 8088:8000
      - 7227:7227 #optional
    restart: unless-stopped

  nextcloud_postgres: # DB for Nextcloud
    image: postgres
    container_name: nextcloud_postgres
    restart: always
    volumes:
      - nextcloud_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=nextcloud
      - POSTGRES_USER=nextcloud

  nextcloud: # Nextcloud
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8081:80
    links:
      - postgres
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped

  ## Monitoring Stack:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    command: --config-directory /etc/telegraf/telegraf.d
    depends_on:
      - influxdb
    networks:
      - influxdb
    volumes:
      - ./monitoring/telegraf:/etc/telegraf
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      influxdb:
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  nextcloud_postgres:
  nextcloud:
  grafana-storage:
  influxdb-storage:

networks:
  influxdb:
```

To your question: Yes, exactly. Thats the way how to put a `compose` stack into `portainer`.

**Comment by hemertje** [comment]
Many thanks again!
Overlooked that too ;(

Deployment just finshed, all Apps running now ;)

<img width="1172" alt="Schermafbeelding 2020-04-30 om 18 13 32" src="https://user-images.githubusercontent.com/45018786/80733700-54fea900-8b0e-11ea-9627-55d99eb852be.png">

May I ask you two some small questions?

1) With previous https://github.com/coderaiser/cloudcmd/issues/288 Cloudcmd I couldn't see the "data" disk under Mount, with the container 

> team0/cloudcmd

there was none... now I can:
<img width="710" alt="Schermafbeelding 2020-04-30 om 18 33 25" src="https://user-images.githubusercontent.com/45018786/80735678-57aecd80-8b11-11ea-8450-6fe023b83f91.png">

But how to see other "SharedFolders" as well?
<img width="158" alt="Schermafbeelding 2020-04-30 om 18 34 25" src="https://user-images.githubusercontent.com/45018786/80735663-5382b000-8b11-11ea-86a2-c1e554b2648e.png">

Should be something with the user/owner of Cloudcmd, but what?
How to give Cloudcmd "sudo" rights to view/show all directories and files?


2) On my Wish / Todo list is installing Pi-Hole on the SBC ROCKPro64 
But the docker-compose example https://github.com/pi-hole/docker-pi-hole , stated Version 3, not version 2 

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

While Stack inside Portainer tells us: 
This stack will be deployed using the equivalent of docker-compose. Only Compose file format version 2 is supported at the moment. 

Via Heimdall it is possible to add Pi-Hole, but it is asking a IP-Adress, this is the IP-Address of the NAS added with the wanted port?
